use "gfx";

func main(args) {
	if gfx.init() == 0 {
		println("Failed to init gfx!");
		return;
	}
	
	if gfx.create_window("Hello BS!", 800, 600, 0) == 0 {
		println("Failed to create gfx window!");
		return;
	}
	
	var smile = gfx.create_texture("tests/res/smile.bmp");
	if type(smile) == "null" {
		println("Failed to load smile.bmp!");
		return;
	}
	println("smile.width: ", smile.width, ", smile.height: ", smile.height);
	
	var running = 1;
	
	var x = 0;
	var y = 0;
	
	while running {
		gfx.clear();
		
		gfx.draw_texture(smile, x, y);
		x = x + 0.01;
		y = y + 0.01;
		
		gfx.present();
		gfx.update();
		if gfx.should_close() {
			running = 0;
		}
	}
}