use "gfx";
import "vec2.bs";

func main(args) {
	if gfx.init() == 0 {
		println("Failed to init gfx!");
		return;
	}
	
	if gfx.create_window("Hello BS!", 800, 600, 0) == 0 {
		println("Failed to create gfx window!");
		return;
	}
	
	var smile = gfx.create_texture("tests/res/smile.bmp");
	if type(smile) == "null" {
		println("Failed to load smile.bmp!");
		return;
	}
	println("smile.width: ", smile.width, ", smile.height: ", smile.height);
	
	var running = 1;
	
	var pos = vec2(0, 0);
	var speed = 0.1;
	
	while running {
		gfx.clear();
		
		gfx.draw_texture(smile, pos.x, pos.y);
		
		var delta = vec2(0, 0);
		if gfx.get_key_state(gfx.KEY_LEFT) {
			delta.x = -1;
		} else if gfx.get_key_state(gfx.KEY_RIGHT) {
			delta.x = 1;
		}
		
		if gfx.get_key_state(gfx.KEY_UP) {
			delta.y = -1;
		} else if gfx.get_key_state(gfx.KEY_DOWN) {
			delta.y = 1;
		}
		var norm = delta:normalized();
		var normmul = norm:mul(speed);
		pos = pos:add(normmul);
		
		gfx.present();
		gfx.update();
		if gfx.should_close() {
			running = 0;
		}
	}
}