use "gfx";
import "vec2.bs";

func main(args) {
	if !gfx.init() {
		println("Failed to init gfx!");
		return;
	}
	
	if !gfx.create_window("Hello BS!", 800, 600, 0) {
		println("Failed to create gfx window!");
		return;
	}
	
	var smile = gfx.create_texture("tests/res/smile.bmp");
	if type(smile) == type(null) {
		println("Failed to load smile.bmp!");
		return;
	}
	println("smile.width: ", smile.width, ", smile.height: ", smile.height);
	
	var pos = vec2(0, 0);
	var speed = 0.1;
	
	while !gfx.should_close() {
		gfx.clear();
		
		gfx.draw_texture(smile, pos.x, pos.y);
		
		var delta = vec2(0, 0);
		if gfx.get_key_state(gfx.KEY_LEFT) {
			delta.x = -1;
		} else if gfx.get_key_state(gfx.KEY_RIGHT) {
			delta.x = 1;
		}
		
		if gfx.get_key_state(gfx.KEY_UP) {
			delta.y = -1;
		} else if gfx.get_key_state(gfx.KEY_DOWN) {
			delta.y = 1;
		}
		var norm = delta:normalized();
		pos = pos:add(norm:mul(speed));
		
		gfx.present();
		gfx.update();
	}
}