var v00 = "1";
var v01 = "2";
var v02 = "3";

var v10 = "4";
var v11 = "5";
var v12 = "6";

var v20 = "7";
var v21 = "8";
var v22 = "9";

var player1 = "X";
var player2 = "O";

func print_table() {
	println("   |   |   ");
	println(" ", v00, " | ", v01, " | ", v02);
	println("___|___|___");
	
	println("   |   |   ");
	println(" ", v10, " | ", v11, " | ", v12);
	println("___|___|___");
	
	println("   |   |   ");
	println(" ", v20, " | ", v21, " | ", v22);
	println("   |   |   ");
}

func check_win(player) {
	if v00 == player && v01 == player && v02 == player {
		return 1;
	}
	if v10 == player && v11 == player && v12 == player {
		return 1;
	}
	if v20 == player && v21 == player && v22 == player {
		return 1;
	}
	
	if v00 == player && v10 == player && v20 == player {
		return 1;
	}
	if v01 == player && v11 == player && v21 == player {
		return 1;
	}
	if v02 == player && v12 == player && v22 == player {
		return 1;
	}
	
	if v00 == player && v11 == player && v22 == player {
		return 1;
	}
	if v02 == player && v11 == player && v20 == player {
		return 1;
	}
	
	return 0;
}

func get_square(n) {
	if n == 1 {
		return v00;
	} else if n == 2 {
		return v01;
	} else if n == 3 {
		return v02;
	} else if n == 4 {
		return v10;
	} else if n == 5 {
		return v11;
	} else if n == 6 {
		return v12;
	} else if n == 7 {
		return v20;
	} else if n == 8 {
		return v21;
	} else if n == 9 {
		return v22;
	}
	
	return null;
}

func set_square(n, player) {
	if n == 1 {
		v00 = player;
	} else if n == 2 {
		v01 = player;
	} else if n == 3 {
		v02 = player;
	} else if n == 4 {
		v10 = player;
	} else if n == 5 {
		v11 = player;
	} else if n == 6 {
		v12 = player;
	} else if n == 7 {
		v20 = player;
	} else if n == 8 {
		v21 = player;
	} else if n == 9 {
		v22 = player;
	}
}

func get_player_input(player, other_player) {
	var nstring = input("'", player, "' select your square: ");
	println();
	var n = str2num(nstring);
	if type(n) == "null" {
		println("Please enter a number!");
		print_table();
		return get_player_input(player, other_player);
	} else if n < 1 || n > 9 {
		println("Please enter a number between 1 and 9!");
		print_table();
		return get_player_input(player, other_player);
	} else {
		var sq = get_square(n);
		if type(sq) == "null" {
			println("Your number is between 1 and 9 but not an integer! Bad player!");
			print_table();
			return get_player_input(player, other_player);
		}
		var sqn = str2num(sq);
		if type(sqn) == "null" {
			println("Square is already occupied, please select another one!");
			print_table();
			return get_player_input(player, other_player);
		}
	}
	
	return n;
}

func play_round(player, other_player) {
	print_table();
	var n = get_player_input(player, other_player);
	set_square(n, player);
}

//TODO:
// - Use tables instead of this stupid var stuff
// - Add some way to convert or floor numbers, that way 8.8 -> 8
func main(args) {
	var current_player = 0;
	var round = 0;
	
	while(1) {
		if current_player == 0 {
			// player1
			play_round(player1, player2);
			if check_win(player1) {
				println(player1, " won the game!");
				print_table();
				return;
			} else {
				current_player = 1;
			}
		} else {
			// player2
			play_round(player2, player1);
			if check_win(player2) {
				println(player2, " won the game!");
				print_table();
				return;
			} else {
				current_player = 0;
			}
		}
		
		round = round + 1;
		if round == 9 {
			print_table();
			println("It's a tie!");
			return;
		}
	}
}